server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/
  instance:
    instance-id: configclient1
    prefer-ip-address: true



spring:
  application:
    name: configclient

